Update cliques to initialize pivotdonenbrs
pivotdonenbrs is not in a high enough scope to be seen between when it is defined and when it is referenced the second time.  Without this change I get:

```
ERROR: pivotdonenbrs not defined
 in maximal_cliques at /home/user/.julia/v0.3/Graphs/src/cliques.jl:125
while loading solver.jl, in expression starting on line 38
```